# Generated by Django 5.0.6 on 2024-08-01 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='policy',
        ),
        migrations.DeleteModel(
            name='Claim',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Policy',
        ),
    ]
