# Generated by Django 5.0.6 on 2024-08-02 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='policy',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='User',
        ),
        migrations.DeleteModel(
            name='Claim',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Policy',
        ),
    ]
